name: SanntiS basic test with preprocessed files

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v7.3.1
        with:
          enable-cache: true

      - name: Install HMMER
        run: sudo apt-get install -y hmmer

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run pytest-workflow with preprocessed files
        run: uv run pytest --tag sanntis_with_preprocessed_files
